import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Callable
from chara.common import Chara
from ..nlu_training import NluTrainingPipeline, NluTrainingReport
from ..ner_training import NerTrainingPipeline, NerTrainingReport
from .store import NluDatasetStore


@dataclass
class NluPipelineReport:
    records: int
    nlu: NluTrainingReport
    ner: NerTrainingReport | None

    def __str__(self):
        lines = [f'Dataset: {self.records} records', str(self.nlu)]
        if self.ner is not None:
            lines.append(str(self.ner))
        return '\n'.join(lines)


class NluPipeline:
    """
    The whole NLU of NluRecognitionSetup: the text dataset is generated by `generator`,
    then KenLM, the Chroma index and the slots adapter are trained on it and deployed.

    The dataset is cumulative: each call of `generate_round` adds a new round of phrases to `store`,
    and the earlier rounds stay. The generation of a round is cached in its own folder,
    so a round that failed in the middle continues on the next call instead of starting anew.
    The training is cached by the content of the dataset and of the negatives (`negatives.txt` next to the dataset):
    it reruns only when they have changed.
    """
    def __init__(self,
                 store: NluDatasetStore,
                 cache_folder: Path,
                 generator: Callable[[], list[dict]] | None,
                 nlu: NluTrainingPipeline | None = None,
                 ner: NerTrainingPipeline | None = None,
                 ):
        self.store = store
        self.cache_folder = cache_folder
        self.generator = generator
        self.nlu = nlu if nlu is not None else NluTrainingPipeline()
        self.ner = ner

    def _generation_folder(self, number: int) -> Path:
        return self.cache_folder / 'generation' / f'round-{number:03d}'

    def next_round(self) -> int:
        """The round that a failed generation left unfinished, or the next one after the stored rounds."""
        self.store.import_legacy_dataset()
        rounds = self.store.rounds()
        number = max(rounds) + 1 if len(rounds) > 0 else 1
        unfinished = [
            n for n in range(1, number)
            if self._generation_folder(n).is_dir() and not self.store.has_round(n)
        ]
        return unfinished[0] if len(unfinished) > 0 else number

    def generate_round(self) -> int:
        if self.generator is None:
            raise ValueError("The pipeline has no generator of the text dataset")
        number = self.next_round()
        Chara.start(self._generation_folder(number))
        records = Chara.call(self.generator, 'generation')()
        self.store.write_round(number, records)
        return number

    def train(self, voice_samples: list[dict] | None = None) -> NluPipelineReport:
        dataset = self.store.read()
        if len(dataset) == 0:
            raise ValueError(f"The dataset in {self.store.folder} is empty: generate a round first")
        negatives = self.store.read_negatives()
        content = self.store.dataset_path.read_bytes() + '\n'.join(negatives).encode('utf-8')
        fingerprint = hashlib.sha256(content).hexdigest()[:16]
        Chara.start(self.cache_folder / 'training' / fingerprint)
        return Chara.call(self._train, 'training')(dataset, negatives, voice_samples)

    def _train(self, dataset: list[dict], negatives: list[str], voice_samples: list[dict] | None) -> NluPipelineReport:
        nlu_report = Chara.call(self.nlu)(dataset, voice_samples)
        ner_report = Chara.call(self.ner)(dataset, negatives) if self.ner is not None else None
        return NluPipelineReport(len(dataset), nlu_report, ner_report)
