from .common import IDependency
from .custom_dependencies import CustomDependencies
from .dependencies import RequirementsDependencies
from .kaia_foundation_dependencies import KaiaFoundationDependencies
from .pytorch_dependencies import PytorchDependencies