import argparse
import time
import webbrowser
from pathlib import Path
from kaia.app import KaiaAppSettings
from foundation_kaia.misc import Loc
from foundation_kaia.fork import Fork
from avatar.app import compile_frontend
from avatar.daemon import NluRecognitionSetup
from brainbox import BrainBox
from brainbox.deciders import WhisperKenLM, Chroma, LlamaLoraSFTTrainer, LlamaLoraServer
from chara.common import Chara
from chara.nlu.nlu_training import NluTrainingPipeline, load_nlu_datasets
from chara.nlu.ner_training import NerTrainingPipeline
from chara.nlu.nlu_pipeline import NluDatasetStore, NluPipeline


parser = argparse.ArgumentParser()
parser.add_argument('--datasets', default=str(Chara.Apis.content_folder / 'nlu/datasets'),
                    help='Folder with text-dataset.json and, optionally, to_zip/samples.json')


if __name__ == '__main__':
    args = parser.parse_args()
    datasets = Path(args.datasets)
    _, voice_samples = load_nlu_datasets(datasets)

    working_folder = Loc.data_folder / 'demo'
    compile_frontend(working_folder / 'avatar' / 'frontend')

    settings = KaiaAppSettings()
    settings.brainbox.deciders_files_in_kaia_working_folder = False
    settings.custom_avatar_resources_folder = Loc.root_folder/'kaia/app/files/avatar-resources'
    ner = NerTrainingPipeline()
    settings.brainbox_setup.up(WhisperKenLM).up(Chroma).up(LlamaLoraServer, parameter=ner.model_id).up(LlamaLoraSFTTrainer)
    settings.avatar_processor.stt_setup = NluRecognitionSetup(slots_adapter=ner.ADAPTER, slots_model=ner.model_id)
    app = settings.create_app(working_folder)

    with Fork(app.brainbox_server):
        app.brainbox_api.wait_for_connection(30)
        settings.brainbox_setup.execute(app.brainbox_api)

        # Trains on the stored dataset, restored from the cache while the dataset is the same.
        # The dataset itself is generated by chara/nlu/run_nlu_training.py, which is too long for the start of Kaia.
        # A separate client: the app's one is pickled into the forks, and API clients keep the last request,
        # which for uploads holds a generator that cannot be pickled.
        Chara.Apis.brainbox_api = BrainBox.Api(app.brainbox_api.base_url)
        pipeline = NluPipeline(NluDatasetStore(datasets), Chara.Apis.cache_folder / 'nlu', None, NluTrainingPipeline(), ner)
        print(pipeline.train(voice_samples))

        app.get_fork_app(None).run()
        app.avatar_api.wait_for_connection(30)

        webbrowser.open('http://127.0.0.1:13002')
        while True:
            time.sleep(1)
